### ISSUE TITLE
How not to create a root node?

### ISSUE THREAD

**Issue by oovm** [antlr/antlr4-intellij-adaptor#39]
I found that there is always a separate root node under `PsiFile`.

Is there a way to remove the grammar root node and let its child nodes belong to `PsiFile`?

---

And I found that the first comment does not belong to the first statement, but to its root node, causing problems when I query the PsiDocument.

![image](https://github.com/antlr/antlr4-intellij-adaptor/assets/17541209/9cdcf02f-e354-4bd0-aa71-91a979733251)

**Comment by ris58h** [comment]
Could you provide a link to your ANTLR grammar?

**Comment by bjansen** [comment]
@oovm I guess you could try overriding `ANTLRParserAdaptor#createListener` to instantiate a custom `ANTLRParseTreeToPSIConverter` in which you would override `enterEveryRule()` and `exitEveryRule()` to ignore `ValkyrieProgramNode`s. Then your first comment would probably be at the same level as the first `expression_root` node.

Are you trying to get rid of `ValkyrieProgramNode` only because of the problem with the first comment, or for other reasons?
